# Generated by Django 3.2.5 on 2021-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211118_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
