# Generated by Django 3.2.5 on 2021-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.IntegerField(choices=[(1, 'participant'), (2, 'administrator'), (3, 'invitee')]),
        ),
    ]
